### ISSUE TITLE
Vérifier contrat assurance AESS

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/Gestion#1]

**Comment by DarkInfinitePotato** [comment]
En ce qui concerne les resposabilités civiles générales, on a bien fait de demander à ce que ce soit voter en AG puisqu'ainsi on se protège avec l'appuie du pouvoir de l'assemblée générale comme quoi on soutien les CS Games avec leur événement.

Pour ce qui est de l'assurance responsabilité civile des CS Games, j'ai pas trouvé de source exacte pour confirmer ce que je dis, mais s'il y a plusieurs contrats d'assurance distincs, alors on peut faire une réclamation pour chacun des contrats. La logique étant que pour chaque contrat d'assurance, une réclamation soit faite. Donc, on pourrait proposer en AG que la première réclamaiton soit faite par l'assurance des CS Games et que s'il y a vraiment beaucoup de dommages dépassant les 3 millions $, alors une réclamation d'asurance sera faite via les assurances de l'AESS.

C'est un peu comme ça que je comprends tout le charabia du monde de l'assurance, je peux toujours valider l'info avec mes profs si vous voulez être certain.e.s à 100%, mais pour vrai, ce serait logique que chaque contrat soit indépendant en soi et qu'on puisse réclamer un montant pour chaque contrat.

Exemple: L'AESS pourrait être assuré avec plusieurs compagnies d'assurance. Pour chacun des contrats, l'AESS pourrait faire une réclamation. (Ça me semble plus simple à comprendre expliquer ainsi)

**Comment by PermAESS** [comment]
OK fait que ya pas de trouble pour que l'aess aide les CSGAMES du moment que l'AG vote pour ?

**Comment by DarkInfinitePotato** [comment]
C'est exacte!

2015-10-21 14:31 GMT-04:00 PermAESS <notifications@github.com>:
