### ISSUE TITLE
Faire le tri, dans la liste câlin.

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/Gestion#13]

**Comment by PermAESS** [comment]
@AESSUQAM/executif  :

1.  Hélo, par courriel, proposait de prendre la décision des sujets et de leur ordre de priorité à amener à Calin en exec le 23 octobre. Or, la secrétaire de Monsieur Calin insiste tout de même pour connaitre l'ordre du jour de la rencontre. Qu'est-ce qu'on fait?

2.  Aussi, j'avais oublié un autre sujet (hésitez pas à le faire savoir à tous et toutes s'il y en a d'autres). C'est le sujet du paiement des frais de scolarité par carte de crédit.

**Comment by tardigrade-critique** [comment]
Hello ! 
Je proposerais de quand même envoyer la liste à Câlin. Au pire, on ajoutera des sujets à la conversation qui n'était pas prévu. Je suis certaine qu'il va pas pas nous jeter dehors si on le fait.
Selon mes notes la liste devrait ressembler à cela:
    Pause commune
    Proposition trash d'un prof pour fermer des programmes automatiquement
    Local info-24hrs
    Frais «afférents» aux cours en Science
    Paiment des frais de scolarité par carte de crédit
    Coupure en sciences (Fermeture du programme de génie et micro-électronique)

Est-ce que tu pourrais envoyer un courriel à Câlin pour l'informer de nos points? @PermAESS
Merci full !

**Comment by PermAESS** [comment]
Salut.

Je n'ai pas grand-chose à dire, c'est vrai que c'est peut-être pas grave 
si la liste est trop longue ou pas assez. Je vous laisse décider.

Mais pour vrai, ceci est plutôt un test. Je réponds à ce message 
directement de la boite courriel et je suis curieux de voir ce que ça fait.

Tourlou!


JS

Le 2015-10-15 17:05, tardigrade-critique a écrit :
>
> Hello !
> Je proposerais de quand même envoyer la liste à Câlin. Au pire, on 
> ajoutera des sujets à la conversation qui n'était pas prévu. Je suis 
> certaine qu'il va pas pas nous jeter dehors si on le fait.
> Selon mes notes la liste devrait ressembler à cela:
> Pause commune
> Proposition trash d'un prof pour fermer des programmes automatiquement
> Local info-24hrs
> Frais «afférents» aux cours en Science
> Paiment des frais de scolarité par carte de crédit
> Coupure en sciences (Fermeture du programme de génie et 
> micro-électronique)
>
> Est-ce que tu pourrais envoyer un courriel à Câlin pour l'informer de 
> nos points? @PermAESS <https://github.com/PermAESS>
> Merci full !
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/AESSUQAM/Gestion/issues/13#issuecomment-148521060>.
>

-- 
Jean-Sébastien Crépeau
Adjoint à l'exécutif
Association étudiante du secteur des sciences de l'UQAM (AESS)
Local SH-R530
Pavillon Sherbrooke, 200 rue Sherbrooke O. H2X 3P2
Téléphone: 514-987-0308
aess@aessuqam.org
http://www.aessuqam.org
