### ISSUE TITLE
Discussion causerie Tisane

### ISSUE THREAD

**Issue by PermAESS** [AESSUQAM/Gestion#19]
Squelette de discussion : 
--------------------------------

1. État de la situation :   
	* UQAM  
		* Étudiante  
		* Syndicat  
	* Québec   

2. Qu'est-ce que ça change au niveau individuel (économique, social, psychologique).    

3. Comment peut-on venir rétablir/amélioré nos dynamique collective.  

4. Comment répondre aux besoins individuels ?

5. Comment est-ce vécu dans le milieu universitaire, en science ? :

	* En tant qu'étudiante, profésseur, chargée de cours, employée, participants à la vie universitaire ?

	* En association étudiantes, syndicats, groupe étudiants ? 

@AESSUQAM/executif vos retour ?

**Comment by tardigrade-critique** [comment]
Hello !

C'est très bien comme squelette de discussion. Cependant, j'aurais quelques
points à revisiter. D'abord, je me demandais si l'aspect individuel n'était
pas un peu trop prédominant dans le squelette au détriment de l'aspect plus
collectif, considérant que l'austérité attaque principalement les
collectivités.  Je me demandais aussi si on pourrait mettre un point qui
est plus spécifiquement sur l'austérité et sa définition pour les personnes
présentes qui ne sont pas familière avec le concept. Je serais aussi d'avis
que le point 5 pourrait être intégré dans le point 1, car ça concerne la
description de l'état actuel.
Je sais pas qui est l'auteur.e du squelette, mais on pourrait en discuter.
Bonne soirée !
Émilie
