### ISSUE TITLE
Contacter cédric Relever RBC

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/Gestion#2]

**Comment by DarkInfinitePotato** [comment]
Cédric est contacté, je suis en attente de sa réponse.

**Comment by DarkInfinitePotato** [comment]
Voici ce que Cédric m'a répondu:
Salut !

Merci du rappel. Finalement je croyais encore y avoir accès, mais on dirait que ce n'est pas le cas.... En tout les cas, il faut se donner rdv la bas !

Ced
