### ISSUE TITLE
Acheter des friandises magiques

### ISSUE THREAD

**Issue by elianed** [AESSUQAM/Gestion#26]
@KarelleD et Nancy

**Comment by KarelleD** [comment]
Acheté:
1X boite 90 mini barres de chocolat
2X boite de 70 petits sacs de jujubes maynards
2X boite de cancy corn (petits triangles blanc-orange-jaune)
1X sac de suçons "eyeball"
1X sac de boules de gomme surette
total: 29,73$

**Comment by nabla-hmu** [comment]
Comme Karelle a déjà acheté beaucoup de choses. J'ai juste acheté une boîte de 90 mini chocolats sans arachides et une boîtes de 90 d'un mélange de skittles et de pâte à macher (toujours sans arachides). Pour un total de 17,10$ si c'est pas assez plus je peux y retourner.

**Comment by ventilooo** [comment]
Tout est good de ce côté ?
