### ISSUE TITLE
Contacter des gens pour l'AG de grève

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/Gestion#3]

**Comment by DarkInfinitePotato** [comment]
J'ai publier sur un groupe de gens militants pour rechercher des bénévoles.
À date j'ai mon coloc (Félix Morin) qui est intéressé à faire l'animation d'une salle secondaire.

J'ai aussi contacté Sophie Rioux pour l'animation de l'AG, je suis en attente d'une réponse de sa part.

**Comment by DarkInfinitePotato** [comment]
Sophie Rioux m'a répondu et elle ne pourra malheureusement pas animer notre AG de grève puisqu'elle travaille ce jour là.

**Comment by tardigrade-critique** [comment]
Wouhou ! On a une animatrice !! 
Alexandra Zawadski-Turcotte a confirmé. Ses coordonnées, si jamais il y
a quoi que ce soit :
514-654-4506
alexzt4@hotmail.com
