### ISSUE TITLE
Trouver praésidium AG de grève

### ISSUE THREAD

**Issue by ventilooo** [AESSUQAM/Gestion#8]
Qui s'en charge ?

**Comment by PermAESS** [comment]
Émilie a envoyé un appel sur le syndicat des praésidium sur facebook !

**Comment by PermAESS** [comment]
On a trouvé???

**Comment by tardigrade-critique** [comment]
Au secrétariat :

**Comment by PermAESS** [comment]
Faut le dire à Nancy!! Première personne qui la voit lui dit de pas arrêter les recherches!!!

**Comment by PermAESS** [comment]
@AESSUQAM/executif
